fix(base-cluster/kube-prometheus-stack): only register healthcheck if enabled on both sides
teutonet/teutonet-helm-charts pull request #1052
Opened 2024-07-29 11:39 UTC by cwrau

2024-08-27 11:47 UTC, tasches requested changes
there is a directory included which should not be there.
**crossplane-anynines/**

2024-08-30 14:21 UTC, tasches requested changes

2024-08-30 14:21 UTC, tasches commented on charts/base-cluster/templates/monitoring/deadMansSwitch/registration.yaml
>                  curl --silent --show-error --fail --retry 5 --max-time 30 "https://hc-ping.com/$PING_KEY/$checkName"
the line above. I tried to setup myself and it did not work. So I made the API call myself and got the Error 400 Bad Request. After some searching in deeper I received the error that something is incorrect with the channel. So I deleted the channel part from the request and it worked. Maybe I did something wrong in the first place of the configuration or this is a bug

2024-09-03 09:10 UTC, tasches commented on charts/base-cluster/templates/monitoring/deadMansSwitch/registration.yaml
>                  curl --silent --show-error --fail --retry 5 --max-time 30 "https://hc-ping.com/$PING_KEY/$checkName"
an integration in healthchecks.io with the global cluster name must be configured. (According to the documentation)

2024-11-18 14:53 UTC, tasches approved these changes

2024-11-26 08:54 UTC, marvinWolff approved these changes

2024-12-02 07:57 UTC, marvinWolff approved these changes

2025-01-28 10:17 UTC, merged