feat(base-cluster/nginx): add possibility to disable ingress
teutonet/teutonet-helm-charts pull request #489
Opened 2023-08-07 12:37 UTC by marvinWolff

Add ability to disable ingress.

2023-08-08 12:43 UTC, cwrau commented
You're missing the `if` in

- [ ] https://github.com/teutonet/teutonet-helm-charts/blob/93b4747ddef340470c27162347971515afb9ab59/charts/base-cluster/templates/global/cluster-ingress.yaml#L1-L0

2023-08-08 12:44 UTC, cwrau requested changes

2023-08-08 12:44 UTC, cwrau commented on charts/base-cluster/templates/monitoring/kube-prometheus-stack/_helpers.yaml
> +  enabled: {{ .context.Values.ingress.enabled }}
That's not a supported situation.
If you want to use the included ingress configuration you have to use the included ingress controller.

If you want to provide your own ingress controller you have to create your own ingresses for the built-in resources.

2023-08-23 08:13 UTC, cwrau requested changes

2023-08-23 08:13 UTC, cwrau commented on charts/base-cluster/templates/monitoring/kube-prometheus-stack/_helpers.yaml
> +  enabled: {{ .context.Values.ingress.enabled }}
You don't need to do both, and thinking about it, I think I would prefer the check in the `if`

2023-08-28 13:57 UTC, cwrau submitted a review, later dismissed

2023-09-08 09:45 UTC, tasches requested changes
the namespace ingress-nginx should not be created if ingress is disabled

2023-09-26 08:00 UTC, marvinWolff commented
> the namespace ingress-nginx should not be created if ingress is disabled

Added :+1:

2023-09-26 08:20 UTC, cwrau requested changes
Ah, you're also missing the dashboard in grafana

And the clusterissuer http01 solver

2023-09-28 11:36 UTC, tasches requested changes
I guess the helmrepository ingress-nginx and the grafana dashboard can also be excluded if the nginx is disabled.
Also there is a regex left behind for that namespace in alertmanager.additionalAlertRelabelConfigs which can be left as it is but is not necessary if the namespace does not exist.

2023-09-28 12:45 UTC, marvinWolff commented
I've now disabled the dashboards and disabled the cluster issuer if the ingress is disabled.

2023-09-29 07:19 UTC, cwrau approved these changes

2023-10-05 14:23 UTC, tasches approved these changes

2023-10-06 12:40 UTC, merged