fix(base-cluster/kyverno): fix excluded namespaces
teutonet/teutonet-helm-charts pull request #608
Opened 2023-10-13 09:42 UTC by marvinWolff

Kyverno decided to add a key before the excluded namespaces..

2023-11-22 14:33 UTC, cwrau approved these changes

2023-11-22 14:35 UTC, cwrau requested changes

2023-11-22 14:35 UTC, cwrau commented on charts/base-cluster/templates/kyverno/kyverno.yaml
> +                values: {{- include "base-cluster.kyverno.ignoredNamespaces" . | nindent 18 }}
```suggestion
                values: {{- include "base-cluster.kyverno.ignoredNamespaces" . | nindent 20 }}
```

2023-11-23 13:00 UTC, tasches approved these changes

2023-11-23 13:29 UTC, cwrau approved these changes

2023-11-23 13:52 UTC, merged