feat(base-cluster/limitrange-quotas): add limitrange and resource quota
teutonet/teutonet-helm-charts pull request #673
Opened 2023-12-08 14:03 UTC by marvinWolff

Add limitRanges and Quotas 

Ref.: https://github.com/teutonet/teutonet-helm-charts/issues/655

2023-12-18 12:43 UTC, cwrau commented
Can you add a CI values yaml with some values set and not set and so on?

2023-12-18 12:44 UTC, cwrau requested changes
Can you add a CI values yaml with some values set and not set and so on?

2023-12-18 12:47 UTC, cwrau requested changes

2023-12-18 12:47 UTC, cwrau commented on charts/base-cluster/templates/global/namespaces.yaml
> +      {{- with $namespace.resources.defaults.limits -}}
Could you make these fields templatable?

2023-12-18 12:47 UTC, cwrau commented on charts/base-cluster/templates/global/namespaces.yaml
> +      {{- with $namespace.resources.defaults.requests -}}
And these as well

2023-12-18 12:47 UTC, cwrau commented on charts/base-cluster/templates/global/namespaces.yaml
> +  {{- with $namespace.resources.quotas -}}
And these as well

2023-12-18 12:47 UTC, cwrau commented on charts/base-cluster/templates/global/namespaces.yaml
> +  hard: {{- $quotas | toYaml | nindent 4 }}
```suggestion
  {{- with $namespace.resources.quotas -}}
  hard: {{- . | toYaml | nindent 4 }}
```

2023-12-18 12:47 UTC, cwrau commented on charts/base-cluster/templates/global/namespaces.yaml
> +  {{- $quotas := dict -}}
```suggestion
```

2024-01-12 10:01 UTC, marvinWolff commented
> Can you add a CI values yaml with some values set and not set and so on?

This is done, isn't it?

2024-01-15 14:22 UTC, cwrau approved these changes

2024-01-15 14:22 UTC, cwrau commented on charts/base-cluster/values.yaml
If you don't want to add resource defaults for other namespaces, this looks fine to me 👌

2024-01-23 14:16 UTC, merged